const PROJECTS_PREFIX = "PROJECTS_";

// Project List
const LIST_PREFIX = PROJECTS_PREFIX + "LIST_";

export const LIST = {
    SET: LIST_PREFIX + "SET",
    SET_AND_ACTIVE_FIRST: LIST_PREFIX + "SET_AND_ACTIVE_FIRST",
    ADD_PROJECT: LIST_PREFIX + "ADD_PROJECT",
    REMOVE_PROJECT: LIST_PREFIX + "REMOVE_PROJECT",
}


// Active project
const ACTIVE_PREFIX = PROJECTS_PREFIX + "ACTIVE_";

export const ACTIVE = {
    SET: ACTIVE_PREFIX + "SET",
    UPDATE: ACTIVE_PREFIX + "UPDATE",
    FETCH: ACTIVE_PREFIX + "FETCH"
}


// Chapters
const CHAPTERS_PREFIX = ACTIVE_PREFIX + "CHAPTERS_"

export const CHAPTERS = {
    ADD: CHAPTERS_PREFIX + "ADD",
    REMOVE: CHAPTERS_PREFIX + "REMOVE",
    UPDATE: CHAPTERS_PREFIX + "UPDATE"
}


// Steps
const STEPS_PREFIX = ACTIVE_PREFIX + "STEPS_"

export const STEPS = {
    ADD: STEPS_PREFIX + "ADD",
    REMOVE: STEPS_PREFIX + "REMOVE",
    UPDATE: STEPS_PREFIX + "UPDATE"
}


// Tasks
const TASKS_PREFIX = ACTIVE_PREFIX + "TASKS_"

export const TASKS = {
    ADD: TASKS_PREFIX + "ADD",
    REMOVE: TASKS_PREFIX + "REMOVE",
    UPDATE: TASKS_PREFIX + "UPDATE"
}


// Projects
const PROJECTS = {
    LIST,
    ACTIVE,
    CHAPTERS,
    STEPS,
    TASKS
}

export default PROJECTS;

