export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";
export const UPDATE_ACTIVE_PROJECT = "UPDATE_ACTIVE_PROJECT";
export const FETCH_ACTIVE_PROJECT = "FETCH_ACTIVE_PROJECT";
export const SET_PROJECTS = "SET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";

// Idea: active = last updated
export const SET_PROJECTS_ACTIVE_FIRST = "SET_PROJECTS_ACTIVE_FIRST";